const THEME = {
    FONT_SIZE_SMALL: 20,
    FONT_SIZE_MEDIUM: 25,
    FONT_SIZE_LARGE: 30,
    FONT_SIZE_EXTRA_LARGE: 35,
    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_HEAVY: 800,
    FONT_COLOR: 'black',
    BACKGROUND_COLOR: 'white',
    TITLE_COLOR: '#50D890',
    DISABLE_COLOR: '#DFDFDF',
    STRONG_DISABLE_COLOR: '#D8D9CF',
    ACTIVE_COLOR: '#50D890',
    PRIMARY_COLOR: 'rgb(30, 147, 242)',
    SECONDARY_COLOR: 'rgb(238, 167, 2)',
};

export default THEME;
